name: MyBB
markdown: kramdown
highlighter: rouge
category-list: [features]
permalink: pretty
baseurl: /wip.mybb.com

remote_theme: mybb/mybb.com-theme

collections:
  features:
    output: true
  rfcs:
    output: true
    permalink: /about/rfcs/:path/
  keys:
    output: true
    permalink: /download/keys/:path/
  versions:
    output: true

defaults:
  - scope:
      path: ""
      type: versions
    values:
      layout: "version"
      title: ""

sass:
  sass_dir: _sass
  style: compressed

gems:
  - jekyll-redirect-from
  - jekyll-remote-theme

exclude: ["CNAME", "README.md", "CONTRIBUTING.md"]
